name: .NET

on:
  push:
    branches:
      - 'main'
      - 'release/**'
      - 'dev'
      - 'hotfix/**'
      - 'feature/**'
  pull_request:
    branches:
      - 'main'
      - 'release/**'
      - 'dev'
      - 'hotfix/**'
      - 'feature/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch for GitVersion
      run: git fetch --unshallow
    - name: Get Git Version
      uses: docker://gittools/gitversion:latest
      with:
        args: /output buildserver
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test      
      run: dotnet test --no-restore
    - name: Coverlet coverage test
      # You may pin to the exact commit or the version.
      # uses: b3b00/coverlet-action@ea67400f084993d98cfb3e2ec5948197d80a7d4e
      uses: b3b00/coverlet-action@1.1.1
      with:
        # output filename
        #output: # default is ./lcov.info
        # output format : lcov, json, opencover, corbertura, temacity (see coverlet documentation)
        #outputFormat: # default is lcov
        # assemblies, namespances exclusions (see coverlet documentation)
        #excludes: # optional
        # path to unit test project from repository root
        testProject: ./src/tests/Flowmailer.Test/Flowmailer.Test.csproj
    - name: Codecov
      env:
        CODECOV_TOKEN: $CODECOV_KEY
      uses: codecov/codecov-action@v2.0.3
    - name: Pack
      run: dotnet pack --configuration Release -p:PackageVersion=$pv -p:AssemblyVersion=$av -p:FileVersion=$fv '-p:InformationalVersion=$iv-$sha' -o "./packages"
      env:
        pv: ${{ env.GitVersion_NuGetVersionV2 }}
        av: ${{ env.GitVersion_AssemblySemVer }}
        fv: ${{ env.GitVersion_AssemblySemFileVer }}
        iv: ${{ env.GitVersion_FullSemVer }}
        sha: ${{ env.GitVersion_ShortSha }}
    - name: Publish to NuGet
        # Only publish releases or betas to nuget, only publish from main branch
      if: (env.GitVersion_PreReleaseTag == '' || env.GitVersion_PreReleaseTag == 'beta') && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')
      env:
        NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
      #run: echo "PUBLISHING TO NUGET - $GitVersion_InformationalVersion"
      run: dotnet nuget push -s https://www.nuget.org/api/v2/package -k $NUGET_API_KEY ./packages/EducateIt.Flowmailer.*.nupkg
